//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ma.EntityLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_AssessmentAttempt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_AssessmentAttempt()
        {
            this.tb_UserAssessmentAttend = new HashSet<tb_UserAssessmentAttend>();
        }
    
        public long AssessmentAttemptId { get; set; }
        public long UserId { get; set; }
        public long SubjectId { get; set; }
        public long AssessmentId { get; set; }
        public System.DateTime AttemptDate { get; set; }
        public long Attempt { get; set; }
    
        public virtual tb_Assessment tb_Assessment { get; set; }
        public virtual tb_Subject tb_Subject { get; set; }
        public virtual tb_Login tb_Login { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_UserAssessmentAttend> tb_UserAssessmentAttend { get; set; }
    }
}
