//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ma.EntityLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_AnswerView
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_AnswerView()
        {
            this.tb_AssessmentAnswer = new HashSet<tb_AssessmentAnswer>();
            this.tb_CbseAnswer = new HashSet<tb_CbseAnswer>();
            this.tb_OlympiadAnswer = new HashSet<tb_OlympiadAnswer>();
            this.tb_ScholarshipAnswer = new HashSet<tb_ScholarshipAnswer>();
        }
    
        public long AnswerViewId { get; set; }
        public string AnswerView { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_AssessmentAnswer> tb_AssessmentAnswer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_CbseAnswer> tb_CbseAnswer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_OlympiadAnswer> tb_OlympiadAnswer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ScholarshipAnswer> tb_ScholarshipAnswer { get; set; }
    }
}
