//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ma.EntityLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Exam
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Exam()
        {
            this.tb_UserExamAttend = new HashSet<tb_UserExamAttend>();
            this.tb_ExamGroup = new HashSet<tb_ExamGroup>();
            this.tb_ExamQuestion = new HashSet<tb_ExamQuestion>();
            this.tb_ExamRank = new HashSet<tb_ExamRank>();
            this.UserExamResults = new HashSet<UserExamResult>();
        }
    
        public long ExamId { get; set; }
        public string ExamName { get; set; }
        public System.TimeSpan Duration { get; set; }
        public Nullable<System.Guid> ExamGUID { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public bool IsActive { get; set; }
        public bool ActiveStatus { get; set; }
        public string ExamEndDate { get; set; }
        public string ExamStartDate { get; set; }
        public Nullable<bool> UpcomingStatus { get; set; }
        public bool PublishStatus { get; set; }
        public Nullable<bool> PublishResult { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_UserExamAttend> tb_UserExamAttend { get; set; }
        public virtual tb_Exam tb_Exam1 { get; set; }
        public virtual tb_Exam tb_Exam2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ExamGroup> tb_ExamGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ExamQuestion> tb_ExamQuestion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ExamRank> tb_ExamRank { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserExamResult> UserExamResults { get; set; }
    }
}
