//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ma.EntityLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ExamRequest
    {
        public long Id { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<long> ExamId { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<bool> ApprovalStatus { get; set; }
    
        public virtual tb_Login tb_Login { get; set; }
    }
}
