//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ma.EntityLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ExamGroup
    {
        public long ID { get; set; }
        public long ExamId { get; set; }
        public long GroupId { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual tb_Exam tb_Exam { get; set; }
        public virtual tb_Group tb_Group { get; set; }
    }
}
