//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ma.EntityLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_GroupStudent
    {
        public long ID { get; set; }
        public long GroupID { get; set; }
        public long StudentID { get; set; }
        public bool IsActive { get; set; }
    }
}
