//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ma.EntityLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Homework
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Homework()
        {
            this.tb_HomeworkStudent = new HashSet<tb_HomeworkStudent>();
        }
    
        public long HomeworkId { get; set; }
        public long TeacherId { get; set; }
        public long ClassId { get; set; }
        public long PracticeTestId { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public bool IsActive { get; set; }
    
        public virtual tb_Class tb_Class { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_HomeworkStudent> tb_HomeworkStudent { get; set; }
        public virtual tb_PracticeTest tb_PracticeTest { get; set; }
        public virtual tb_Login tb_Login { get; set; }
    }
}
