//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ma.EntityLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_HomeworkStudent
    {
        public long Id { get; set; }
        public long HomeworkId { get; set; }
        public long UserId { get; set; }
        public Nullable<long> AttemptId { get; set; }
        public string Grade { get; set; }
        public bool HomeworkStatus { get; set; }
        public bool IsActive { get; set; }
    
        public virtual tb_Homework tb_Homework { get; set; }
        public virtual tb_PracticeAttempt tb_PracticeAttempt { get; set; }
        public virtual tb_Login tb_Login { get; set; }
    }
}
