//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ma.EntityLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Ipayy
    {
        public long Id { get; set; }
        public long UserId { get; set; }
        public string Status { get; set; }
        public string Tx { get; set; }
        public string R { get; set; }
        public string Cc { get; set; }
        public string Td { get; set; }
        public string Mn { get; set; }
        public string Op { get; set; }
        public string Ts { get; set; }
        public string Ac { get; set; }
        public string Ec { get; set; }
        public Nullable<System.Guid> ParentGuid { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    
        public virtual tb_Login tb_Login { get; set; }
    }
}
