//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ma.EntityLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Login
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Login()
        {
            this.tb_AppRedeemPoints = new HashSet<tb_AppRedeemPoints>();
            this.tb_AssessmentAttempt = new HashSet<tb_AssessmentAttempt>();
            this.tb_Challenge = new HashSet<tb_Challenge>();
            this.tb_Challenge1 = new HashSet<tb_Challenge>();
            this.tb_ClassStudent = new HashSet<tb_ClassStudent>();
            this.tb_DivisionStudent = new HashSet<tb_DivisionStudent>();
            this.tb_ExamRank = new HashSet<tb_ExamRank>();
            this.tb_ExamRequest = new HashSet<tb_ExamRequest>();
            this.tb_Homework = new HashSet<tb_Homework>();
            this.tb_HomeworkSchool = new HashSet<tb_HomeworkSchool>();
            this.tb_HomeworkStudent = new HashSet<tb_HomeworkStudent>();
            this.tb_HomeworkStudentSchool = new HashSet<tb_HomeworkStudentSchool>();
            this.tb_Ipayy = new HashSet<tb_Ipayy>();
            this.tb_MpesePayment = new HashSet<tb_MpesePayment>();
            this.tb_Notification = new HashSet<tb_Notification>();
            this.tb_NotificationUser = new HashSet<tb_NotificationUser>();
            this.tb_OlympiadAttempt = new HashSet<tb_OlympiadAttempt>();
            this.tb_PayByCash = new HashSet<tb_PayByCash>();
            this.tb_PracticePoint = new HashSet<tb_PracticePoint>();
            this.tb_PracticePointDetails = new HashSet<tb_PracticePointDetails>();
            this.tb_RedeemPoints = new HashSet<tb_RedeemPoints>();
            this.tb_ReferFriend = new HashSet<tb_ReferFriend>();
            this.tb_ReferFriend1 = new HashSet<tb_ReferFriend>();
            this.tb_SchoolRating = new HashSet<tb_SchoolRating>();
            this.tb_SubjectExpertSubject = new HashSet<tb_SubjectExpertSubject>();
            this.tb_TeacherSubject = new HashSet<tb_TeacherSubject>();
            this.tb_UnlockedLevel = new HashSet<tb_UnlockedLevel>();
            this.tb_UserAssessmentAttend = new HashSet<tb_UserAssessmentAttend>();
            this.tb_UserExamAttend = new HashSet<tb_UserExamAttend>();
            this.tb_UserLog = new HashSet<tb_UserLog>();
            this.tb_UserOlympiadAttend = new HashSet<tb_UserOlympiadAttend>();
            this.tb_PracticeAttempt = new HashSet<tb_PracticeAttempt>();
            this.tb_Payment = new HashSet<tb_Payment>();
            this.tb_Mark = new HashSet<tb_Mark>();
            this.tb_PAYTM_REQUEST = new HashSet<tb_PAYTM_REQUEST>();
            this.tb_PAYTM_RESPONSE = new HashSet<tb_PAYTM_RESPONSE>();
            this.tb_UserAttend = new HashSet<tb_UserAttend>();
            this.tb_UserPreparationAttend = new HashSet<tb_UserPreparationAttend>();
            this.tb_UserPreparationResult = new HashSet<tb_UserPreparationResult>();
            this.UserExamResults = new HashSet<UserExamResult>();
        }
    
        public long UserId { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public string Email { get; set; }
        public string ContactNo { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string SchoolName { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public Nullable<System.Guid> UserGuid { get; set; }
        public string Location { get; set; }
        public string State { get; set; }
        public string Address { get; set; }
        public string PostalCode { get; set; }
        public Nullable<bool> DisableStatus { get; set; }
        public string ReferenceCode { get; set; }
        public string PromoCode { get; set; }
        public string Pin { get; set; }
        public string Districts { get; set; }
        public Nullable<long> CourseId { get; set; }
        public string FilesName { get; set; }
        public string SessionId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_AppRedeemPoints> tb_AppRedeemPoints { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_AssessmentAttempt> tb_AssessmentAttempt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Challenge> tb_Challenge { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Challenge> tb_Challenge1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ClassStudent> tb_ClassStudent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_DivisionStudent> tb_DivisionStudent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ExamRank> tb_ExamRank { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ExamRequest> tb_ExamRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Homework> tb_Homework { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_HomeworkSchool> tb_HomeworkSchool { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_HomeworkStudent> tb_HomeworkStudent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_HomeworkStudentSchool> tb_HomeworkStudentSchool { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Ipayy> tb_Ipayy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_MpesePayment> tb_MpesePayment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Notification> tb_Notification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_NotificationUser> tb_NotificationUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_OlympiadAttempt> tb_OlympiadAttempt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_PayByCash> tb_PayByCash { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_PracticePoint> tb_PracticePoint { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_PracticePointDetails> tb_PracticePointDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_RedeemPoints> tb_RedeemPoints { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ReferFriend> tb_ReferFriend { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ReferFriend> tb_ReferFriend1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_SchoolRating> tb_SchoolRating { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_SubjectExpertSubject> tb_SubjectExpertSubject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_TeacherSubject> tb_TeacherSubject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_UnlockedLevel> tb_UnlockedLevel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_UserAssessmentAttend> tb_UserAssessmentAttend { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_UserExamAttend> tb_UserExamAttend { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_UserLog> tb_UserLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_UserOlympiadAttend> tb_UserOlympiadAttend { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_PracticeAttempt> tb_PracticeAttempt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Payment> tb_Payment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Mark> tb_Mark { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_PAYTM_REQUEST> tb_PAYTM_REQUEST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_PAYTM_RESPONSE> tb_PAYTM_RESPONSE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_UserAttend> tb_UserAttend { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_UserPreparationAttend> tb_UserPreparationAttend { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_UserPreparationResult> tb_UserPreparationResult { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserExamResult> UserExamResults { get; set; }
    }
}
