//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ma.EntityLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_MpesePayment
    {
        public long MpeseId { get; set; }
        public long UserId { get; set; }
        public string Mcompgtransid { get; set; }
        public string Transrefno { get; set; }
        public string Statuscode { get; set; }
        public string Reason { get; set; }
        public string TxnAmt { get; set; }
        public int PaymeentType { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public bool IsActive { get; set; }
    
        public virtual tb_Login tb_Login { get; set; }
    }
}
