//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ma.EntityLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Notification
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Notification()
        {
            this.tb_Challenge = new HashSet<tb_Challenge>();
            this.tb_NotificationUser = new HashSet<tb_NotificationUser>();
        }
    
        public long NotificationId { get; set; }
        public long FromUserId { get; set; }
        public string Message { get; set; }
        public string ImageLink { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public int NotificationType { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Challenge> tb_Challenge { get; set; }
        public virtual tb_Login tb_Login { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_NotificationUser> tb_NotificationUser { get; set; }
    }
}
