//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ma.EntityLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Olympiad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Olympiad()
        {
            this.tb_OlympiadAttempt = new HashSet<tb_OlympiadAttempt>();
            this.tb_OlympiadChapter = new HashSet<tb_OlympiadChapter>();
        }
    
        public long OlympiadId { get; set; }
        public string OlympiadName { get; set; }
        public System.Guid OlympiadGuid { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public bool IsActive { get; set; }
        public long ClassId { get; set; }
        public Nullable<long> OrderValue { get; set; }
    
        public virtual tb_Class tb_Class { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_OlympiadAttempt> tb_OlympiadAttempt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_OlympiadChapter> tb_OlympiadChapter { get; set; }
    }
}
