//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ma.EntityLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_OlympiadAnswer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_OlympiadAnswer()
        {
            this.tb_UserOlympiadAttend = new HashSet<tb_UserOlympiadAttend>();
        }
    
        public long AnswerId { get; set; }
        public string Answer { get; set; }
        public long QuestionId { get; set; }
        public long AnswerTypeId { get; set; }
        public long AnswerViewId { get; set; }
        public System.Guid AnswerGuid { get; set; }
        public int RightStatus { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime TimeStamp { get; set; }
    
        public virtual tb_AnswerType tb_AnswerType { get; set; }
        public virtual tb_AnswerView tb_AnswerView { get; set; }
        public virtual tb_OlympiadQuestion tb_OlympiadQuestion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_UserOlympiadAttend> tb_UserOlympiadAttend { get; set; }
    }
}
