//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ma.EntityLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_OlympiadChapter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_OlympiadChapter()
        {
            this.tb_OlympiadAttempt = new HashSet<tb_OlympiadAttempt>();
            this.tb_OlympiadTest = new HashSet<tb_OlympiadTest>();
        }
    
        public long ChapterId { get; set; }
        public string ChapterName { get; set; }
        public long OlympiadId { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public System.Guid ChapterGuid { get; set; }
        public Nullable<long> orderValue { get; set; }
    
        public virtual tb_Olympiad tb_Olympiad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_OlympiadAttempt> tb_OlympiadAttempt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_OlympiadTest> tb_OlympiadTest { get; set; }
    }
}
