//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ma.EntityLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_OlympiadTest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_OlympiadTest()
        {
            this.tb_OlympiadAttempt = new HashSet<tb_OlympiadAttempt>();
        }
    
        public long TestId { get; set; }
        public string TestName { get; set; }
        public long ChapterId { get; set; }
        public System.Guid TestGuid { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public long OrderValue { get; set; }
        public System.TimeSpan Duration { get; set; }
        public bool PublishStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_OlympiadAttempt> tb_OlympiadAttempt { get; set; }
        public virtual tb_OlympiadChapter tb_OlympiadChapter { get; set; }
    }
}
