//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ma.EntityLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_OlympiadAttempt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_OlympiadAttempt()
        {
            this.tb_UserOlympiadAttend = new HashSet<tb_UserOlympiadAttend>();
        }
    
        public long Id { get; set; }
        public long UserId { get; set; }
        public long OlympiadId { get; set; }
        public long ChapterId { get; set; }
        public long OlympiadTestId { get; set; }
        public System.DateTime Date { get; set; }
        public long Attempt { get; set; }
        public Nullable<bool> UnlockedStatus { get; set; }
    
        public virtual tb_Login tb_Login { get; set; }
        public virtual tb_Olympiad tb_Olympiad { get; set; }
        public virtual tb_OlympiadChapter tb_OlympiadChapter { get; set; }
        public virtual tb_OlympiadTest tb_OlympiadTest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_UserOlympiadAttend> tb_UserOlympiadAttend { get; set; }
    }
}
