//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ma.EntityLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_PracticeTest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_PracticeTest()
        {
            this.tb_Exercise = new HashSet<tb_Exercise>();
            this.tb_Homework = new HashSet<tb_Homework>();
        }
    
        public long PracticeTestId { get; set; }
        public string PracticeTestName { get; set; }
        public long ChapterId { get; set; }
        public System.Guid PracticeTestGuid { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public long OrderValue { get; set; }
        public System.TimeSpan Duration { get; set; }
        public Nullable<bool> PublishStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Exercise> tb_Exercise { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Homework> tb_Homework { get; set; }
    }
}
