//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ma.EntityLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_PromoCode
    {
        public long PromoId { get; set; }
        public string PromoCode { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public double DiscountPercentage { get; set; }
        public long TotalCount { get; set; }
        public long RemainingCount { get; set; }
        public System.Guid PromoGuid { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime TimeStamp { get; set; }
    }
}
