//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ma.EntityLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_PasswordReset
    {
        public long Id { get; set; }
        public System.Guid UserGuid { get; set; }
        public int UserType { get; set; }
        public System.Guid ResetGuid { get; set; }
        public bool IsExpired { get; set; }
        public System.DateTime TimeStamp { get; set; }
    }
}
