//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ma.EntityLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_PAYTM_REQUEST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_PAYTM_REQUEST()
        {
            this.tb_Payment = new HashSet<tb_Payment>();
            this.tb_PAYTM_RESPONSE = new HashSet<tb_PAYTM_RESPONSE>();
        }
    
        public decimal REQUEST_ID { get; set; }
        public long USER_ID { get; set; }
        public long PAKAGE_ID { get; set; }
        public string MID { get; set; }
        public string ORDER_ID { get; set; }
        public string CUST_ID { get; set; }
        public string TXN_AMOUNT { get; set; }
        public string CHANNEL_ID { get; set; }
        public string WEBSITE { get; set; }
        public string CHECKSUMHASH { get; set; }
        public string MOBILE_NO { get; set; }
        public string EMAIL { get; set; }
        public string INDUSTRY_TYPE_ID { get; set; }
        public string CALLBACK_URL { get; set; }
        public string PAYMENT_MODE_ONLY { get; set; }
        public string AUTH_MODE { get; set; }
        public string PAYMENT_TYPE_ID { get; set; }
        public string BANK_CODE { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime TimeStamp { get; set; }
    
        public virtual tb_Login tb_Login { get; set; }
        public virtual tb_Package tb_Package { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Payment> tb_Payment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_PAYTM_RESPONSE> tb_PAYTM_RESPONSE { get; set; }
    }
}
