//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ma.EntityLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_PaymentTest
    {
        public long PaymentId { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<bool> PaidStatus { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<long> PaymentType { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public Nullable<System.Guid> ParentGuid { get; set; }
        public Nullable<int> PaymentMode { get; set; }
    }
}
