//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ma.EntityLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_PracticeAttempt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_PracticeAttempt()
        {
            this.tb_HomeworkStudent = new HashSet<tb_HomeworkStudent>();
            this.tb_PracticePointDetails = new HashSet<tb_PracticePointDetails>();
            this.tb_UserAttend = new HashSet<tb_UserAttend>();
        }
    
        public long Id { get; set; }
        public long UserId { get; set; }
        public long Levelid { get; set; }
        public System.DateTime Date { get; set; }
        public long Attempt { get; set; }
        public Nullable<bool> UnlockedStatus { get; set; }
        public long SubtopicId { get; set; }
        public long TopicId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_HomeworkStudent> tb_HomeworkStudent { get; set; }
        public virtual tb_Level tb_Level { get; set; }
        public virtual tb_Login tb_Login { get; set; }
        public virtual tb_Subtopic tb_Subtopic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_PracticePointDetails> tb_PracticePointDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_UserAttend> tb_UserAttend { get; set; }
    }
}
