//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ma.EntityLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_PracticeReward
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_PracticeReward()
        {
            this.tb_AppRedeemPoints = new HashSet<tb_AppRedeemPoints>();
            this.tb_RedeemPoints = new HashSet<tb_RedeemPoints>();
        }
    
        public long RewardId { get; set; }
        public long ClassId { get; set; }
        public string RewardName { get; set; }
        public long Range { get; set; }
        public string PictureLink { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_AppRedeemPoints> tb_AppRedeemPoints { get; set; }
        public virtual tb_Class tb_Class { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_RedeemPoints> tb_RedeemPoints { get; set; }
    }
}
