//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ma.EntityLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_PAYTM_RESPONSE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_PAYTM_RESPONSE()
        {
            this.tb_Payment = new HashSet<tb_Payment>();
        }
    
        public decimal RESPONSE_ID { get; set; }
        public decimal REQUEST_ID { get; set; }
        public long USER_ID { get; set; }
        public long PAKAGE_ID { get; set; }
        public string MID { get; set; }
        public string TXNID { get; set; }
        public string ORDERID { get; set; }
        public string BANKTXNID { get; set; }
        public string TXNAMOUNT { get; set; }
        public string CURRENCY { get; set; }
        public string STATUS { get; set; }
        public string RESPCODE { get; set; }
        public string RESPMSG { get; set; }
        public string TXNDATE { get; set; }
        public string GATEWAYNAME { get; set; }
        public string BANKNAME { get; set; }
        public string PAYMENTMODE { get; set; }
        public string CHECKSUMHASH { get; set; }
        public string BIN_NUMBER { get; set; }
        public string CARD_LAST_NUMS { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime TimeStamp { get; set; }
    
        public virtual tb_Login tb_Login { get; set; }
        public virtual tb_Package tb_Package { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Payment> tb_Payment { get; set; }
        public virtual tb_PAYTM_REQUEST tb_PAYTM_REQUEST { get; set; }
    }
}
