//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ma.EntityLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Payment
    {
        public long PaymentId { get; set; }
        public long UserId { get; set; }
        public bool PaidStatus { get; set; }
        public decimal Amount { get; set; }
        public Nullable<long> PaymentType { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public System.Guid ParentGuid { get; set; }
        public Nullable<int> PaymentMode { get; set; }
        public bool IsActive { get; set; }
        public long PackageID { get; set; }
        public System.DateTime Expirydate { get; set; }
        public Nullable<decimal> REQUEST_ID { get; set; }
        public Nullable<decimal> RESPONSE_ID { get; set; }
    
        public virtual tb_Login tb_Login { get; set; }
        public virtual tb_PAYTM_REQUEST tb_PAYTM_REQUEST { get; set; }
        public virtual tb_PAYTM_RESPONSE tb_PAYTM_RESPONSE { get; set; }
    }
}
