//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ma.EntityLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Question()
        {
            this.tb_Answer = new HashSet<tb_Answer>();
            this.tb_UserAttend = new HashSet<tb_UserAttend>();
            this.tb_UserExamAttend = new HashSet<tb_UserExamAttend>();
            this.tb_UserPreparationAttend = new HashSet<tb_UserPreparationAttend>();
        }
    
        public long QuestionId { get; set; }
        public string Question { get; set; }
        public double Mark { get; set; }
        public long QuestionTypeId { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public string Explanation { get; set; }
        public Nullable<double> NegativeMark { get; set; }
        public long LevelID { get; set; }
        public string QuestionImage { get; set; }
        public string AnswerExpImage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Answer> tb_Answer { get; set; }
        public virtual tb_Level tb_Level { get; set; }
        public virtual tb_QuestionType tb_QuestionType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_UserAttend> tb_UserAttend { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_UserExamAttend> tb_UserExamAttend { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_UserPreparationAttend> tb_UserPreparationAttend { get; set; }
    }
}
