//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ma.EntityLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_QuestionType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_QuestionType()
        {
            this.tb_AssessmentQuestion = new HashSet<tb_AssessmentQuestion>();
            this.tb_CbseQuestion = new HashSet<tb_CbseQuestion>();
            this.tb_OlympiadQuestion = new HashSet<tb_OlympiadQuestion>();
            this.tb_Question = new HashSet<tb_Question>();
            this.tb_ScholarshipQuestion = new HashSet<tb_ScholarshipQuestion>();
            this.tb_ScholarshipQuestionTest = new HashSet<tb_ScholarshipQuestionTest>();
        }
    
        public long QuestionTypeId { get; set; }
        public string QuestionType { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_AssessmentQuestion> tb_AssessmentQuestion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_CbseQuestion> tb_CbseQuestion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_OlympiadQuestion> tb_OlympiadQuestion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Question> tb_Question { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ScholarshipQuestion> tb_ScholarshipQuestion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ScholarshipQuestionTest> tb_ScholarshipQuestionTest { get; set; }
    }
}
