//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ma.EntityLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_RedeemPoints
    {
        public long RedeemId { get; set; }
        public long UserId { get; set; }
        public long RewardId { get; set; }
        public string RewardName { get; set; }
        public long Points { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public bool IsActive { get; set; }
        public bool DispatchedStatus { get; set; }
    
        public virtual tb_Login tb_Login { get; set; }
        public virtual tb_PracticeReward tb_PracticeReward { get; set; }
    }
}
