//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ma.EntityLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_SchoolRating
    {
        public long RatingId { get; set; }
        public long UserId { get; set; }
        public long SchoolId { get; set; }
        public string Name { get; set; }
        public int Rating { get; set; }
        public string Comment { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public System.Guid RatingGuid { get; set; }
        public bool ApproveStatus { get; set; }
        public bool IsActive { get; set; }
    
        public virtual tb_Login tb_Login { get; set; }
        public virtual tb_School tb_School { get; set; }
    }
}
