//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ma.EntityLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ScholarshipAttempt
    {
        public long ScholarshipAttemptId { get; set; }
        public long UserId { get; set; }
        public long ExamId { get; set; }
        public System.Guid Guid { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public bool IsActive { get; set; }
    }
}
