//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ma.EntityLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_School
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_School()
        {
            this.tb_Division = new HashSet<tb_Division>();
            this.tb_SchoolRating = new HashSet<tb_SchoolRating>();
        }
    
        public long SchoolId { get; set; }
        public string School { get; set; }
        public string Location { get; set; }
        public string Contact { get; set; }
        public long StateId { get; set; }
        public System.Guid SchoolGuid { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public bool ViewStatus { get; set; }
        public long PostalCode { get; set; }
        public string Description { get; set; }
        public string BannerLink { get; set; }
        public bool DeactivateStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Division> tb_Division { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_SchoolRating> tb_SchoolRating { get; set; }
        public virtual tb_State tb_State { get; set; }
    }
}
