//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ma.EntityLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ScoreRange
    {
        public long ScoreRangeId { get; set; }
        public string RangeName { get; set; }
        public int MinMark { get; set; }
        public int MaxMark { get; set; }
        public string Message { get; set; }
        public int StarRating { get; set; }
        public System.Guid ScoreGuid { get; set; }
        public string LevelName { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public long OrderValue { get; set; }
        public string Grade { get; set; }
    }
}
