//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ma.EntityLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Scholarship
    {
        public long Id { get; set; }
        public string Scholarship { get; set; }
        public long SubjectId { get; set; }
        public System.Guid ScholarshipGuid { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public long OrderValue { get; set; }
        public System.TimeSpan Duration { get; set; }
    
        public virtual tb_Subject tb_Subject { get; set; }
    }
}
