//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ma.EntityLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Subject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Subject()
        {
            this.tb_Assessment = new HashSet<tb_Assessment>();
            this.tb_AssessmentAttempt = new HashSet<tb_AssessmentAttempt>();
            this.tb_Scholarship = new HashSet<tb_Scholarship>();
            this.tb_SubjectExpertSubject = new HashSet<tb_SubjectExpertSubject>();
            this.tb_TeacherSubject = new HashSet<tb_TeacherSubject>();
        }
    
        public long SubjectId { get; set; }
        public string SubjectName { get; set; }
        public System.Guid SubjectGuid { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public bool IsActive { get; set; }
        public Nullable<long> ClassId { get; set; }
        public Nullable<long> OrderValue { get; set; }
        public string BookUrl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Assessment> tb_Assessment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_AssessmentAttempt> tb_AssessmentAttempt { get; set; }
        public virtual tb_Class tb_Class { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Scholarship> tb_Scholarship { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_SubjectExpertSubject> tb_SubjectExpertSubject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_TeacherSubject> tb_TeacherSubject { get; set; }
    }
}
