//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ma.EntityLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Topic
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Topic()
        {
            this.tb_Level = new HashSet<tb_Level>();
            this.tb_Subtopic = new HashSet<tb_Subtopic>();
        }
    
        public long TopicID { get; set; }
        public long SubjectID { get; set; }
        public string TopicName { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime Timestamp { get; set; }
        public long CourseID { get; set; }
        public long PackageID { get; set; }
    
        public virtual tb_Course tb_Course { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Level> tb_Level { get; set; }
        public virtual tb_Package tb_Package { get; set; }
        public virtual tb_Subjects tb_Subjects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Subtopic> tb_Subtopic { get; set; }
    }
}
