//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ma.EntityLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_UserOlympiadAttend
    {
        public long Id { get; set; }
        public long UserId { get; set; }
        public long QuestionId { get; set; }
        public long UserAnswerId { get; set; }
        public long RightAnswerId { get; set; }
        public double Mark { get; set; }
        public System.Guid ParentGuid { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public long OlympiadAttemptId { get; set; }
        public int AttendStatus { get; set; }
    
        public virtual tb_Login tb_Login { get; set; }
        public virtual tb_OlympiadAnswer tb_OlympiadAnswer { get; set; }
        public virtual tb_OlympiadAttempt tb_OlympiadAttempt { get; set; }
        public virtual tb_OlympiadQuestion tb_OlympiadQuestion { get; set; }
    }
}
