//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ma.EntityLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_UserPreparationResult
    {
        public int Id { get; set; }
        public long UserId { get; set; }
        public long PreparationId { get; set; }
        public double Mark { get; set; }
        public long Time { get; set; }
    
        public virtual tb_Login tb_Login { get; set; }
        public virtual tb_Preparation tb_Preparation { get; set; }
    }
}
