//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ma.EntityLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_UserAttend
    {
        public long Id { get; set; }
        public long UserId { get; set; }
        public long QuestionId { get; set; }
        public long UserAnswerId { get; set; }
        public long RightAnswerId { get; set; }
        public double Mark { get; set; }
        public Nullable<System.Guid> ParentGuid { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public long PracticeAttemptId { get; set; }
        public int AttendStatus { get; set; }
        public long LevelId { get; set; }
    
        public virtual tb_Answer tb_Answer { get; set; }
        public virtual tb_Login tb_Login { get; set; }
        public virtual tb_PracticeAttempt tb_PracticeAttempt { get; set; }
        public virtual tb_Question tb_Question { get; set; }
    }
}
