//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ma.EntityLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserExamResult
    {
        public int Id { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<long> ExamID { get; set; }
        public Nullable<double> Mark { get; set; }
    
        public virtual tb_Exam tb_Exam { get; set; }
        public virtual tb_Login tb_Login { get; set; }
    }
}
