//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ma.EntityLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_ExamStudentResult
    {
        public long Expr1 { get; set; }
        public string FirstName { get; set; }
        public long Id { get; set; }
        public double Mark { get; set; }
        public Nullable<long> Examtime { get; set; }
        public Nullable<bool> Expr2 { get; set; }
        public long ExamId { get; set; }
        public long UserId { get; set; }
        public bool IsActive { get; set; }
        public long RightAnswerStatus { get; set; }
        public long UserAnswerId { get; set; }
        public long QuestionId { get; set; }
        public Nullable<System.Guid> ParentGuid { get; set; }
    }
}
